import { Client, Pool, PgWebTransport } from "@ooraini/pgquic";
import "./style.css";
const $ = <T extends HTMLElement>(id: string) =>
  document.getElementById(id) as T;
const log = (text: string, ok = true) => {
  const li = document.createElement("li");
  li.textContent = text;
  li.className = ok ? "ok" : "error";
  $("log").prepend(li);
};

const fileMode = location.protocol === "file:";
const usableRuntime = window.isSecureContext && "WebTransport" in window;

// The dashboard is also shipped as a single portable HTML file. In file mode
// the browser uses an opaque origin, so the gateway must explicitly opt in.
const check = (text: string, ok = true) => {
  const li = document.createElement("li");
  li.textContent = `${ok ? "✓" : "✕"} ${text}`;
  li.className = ok ? "ok" : "error";
  $("checks").append(li);
};

check(
  window.isSecureContext
    ? "Secure context available"
    : "Secure context required: use file:// or a trusted HTTPS origin",
  window.isSecureContext,
);
check(
  "WebTransport" in window
    ? "WebTransport API available"
    : "WebTransport unavailable: use a current browser with HTTP/3 support",
  "WebTransport" in window,
);
if (fileMode) {
  check("Portable file mode active (opaque file origin)");
  check("Gateway must explicitly enable allowNullOrigin");
  ($("connection-settings") as HTMLDetailsElement).open = true;
}

let transport: PgWebTransport;
let pool: InstanceType<typeof Pool>;
const encodedHash = import.meta.env.VITE_PGQUIC_CERT_HASH as string | undefined;
$<HTMLInputElement>("certificate-hash").value = encodedHash ?? "";

function certificateHashes() {
  const encoded = $<HTMLInputElement>("certificate-hash").value.trim();
  if (!encoded) return undefined;
  try {
    const value = Uint8Array.from(atob(encoded), (c) => c.charCodeAt(0));
    if (value.byteLength !== 32) throw new Error("wrong length");
    return [{ algorithm: "sha-256" as const, value }];
  } catch {
    throw new Error(
      "Certificate failure: enter the base64 SHA-256 certificate hash generated by make cert, or clear it when the gateway certificate is locally trusted.",
    );
  }
}

function create() {
  // PgWebTransport supplies node-postgres with one logical PostgreSQL stream
  // per client while reusing the same HTTP/3 connection to the gateway.
  transport = new PgWebTransport({
    url: $<HTMLInputElement>("gateway-url").value.trim(),
    token: () => $<HTMLInputElement>("jwt").value.trim(),
    maxConnections: 10,
    serverCertificateHashes: certificateHashes(),
  });
  pool = new Pool({
    transport,
    max: 10,
    user: "browser_user",
    password: "development-only-password",
    database: "app",
    ssl: false,
    enableChannelBinding: false,
  });
  transport.addEventListener("statechange", render);
  render();
  log("Pool created");
}
function render() {
  const s = transport.state;
  $("status").textContent = s.status;
  $("generation").textContent = String(s.generation);
  $("sessions").textContent = String(s.totalSessions);
  $("streams").textContent = String(s.activeConnections);
}

function actionableErrors(error: unknown): string[] {
  const raw = error instanceof Error ? error.message : String(error);
  const message = raw.toLowerCase();
  if (message.includes("authentication failed"))
    return [
      "Authentication failure: provide a valid control-stream JWT, or disable JWT authentication on the gateway if appropriate.",
    ];
  if (
    message.includes("local network") ||
    message.includes("permission") ||
    (error instanceof DOMException &&
      (error.name === "NotAllowedError" || error.name === "SecurityError"))
  )
    return [
      "Local-network permission denied: allow this file to access devices on your local network in the browser site settings, then retry.",
    ];
  if (
    message.includes("certificate") ||
    message.includes("tls") ||
    message.includes("cert_")
  )
    return [
      "Certificate failure: trust the gateway certificate locally or paste the current base64 serverCertificateHashes value produced by make cert.",
    ];
  if (message.includes("origin") || message.includes("403"))
    return [
      "Gateway rejected Origin: null: enable allowNullOrigin explicitly on the gateway; do not add null to the trusted-origin list.",
    ];
  if (fileMode)
    return [
      `WebTransport connection failed: ${raw}`,
      "Local-network permission may be denied: allow local-network access for this file in browser settings.",
      "Certificate failure is possible: trust the certificate locally or use the current serverCertificateHashes value.",
      "The gateway may be rejecting the opaque file origin: enable allowNullOrigin explicitly and restart it.",
    ];
  return [`WebTransport connection failed: ${raw}`];
}

async function run() {
  ($("run") as HTMLButtonElement).disabled = true;
  try {
    if (!window.isSecureContext)
      throw new Error(
        "WebTransport unavailable: this page is not a secure context. Open dashboard.html with file:// or serve the normal demo over trusted HTTPS.",
      );
    if (!("WebTransport" in window))
      throw new Error(
        "WebTransport unavailable: use a current browser with WebTransport and HTTP/3 support.",
      );
    // These exercises intentionally use the familiar node-postgres API: bound
    // parameters, pooled transactions, prepared statements, notifications,
    // cancellation, and a larger result all travel through WebTransport.
    const result = await pool.query(
      "select id, title from posts where id = $1",
      [1],
    );
    log(`Parameterized query: ${result.rows[0]?.title}`);
    const clients = await Promise.all([
      pool.connect(),
      pool.connect(),
      pool.connect(),
    ]);
    log(`Three Pool clients active over session ${transport.state.sessionId}`);
    await Promise.all(
      clients.map(async (c: any, i: number) => {
        await c.query("begin");
        const r = await c.query("select $1::int as worker", [i + 1]);
        await c.query("commit");
        return r;
      }),
    );
    log("Three independent transactions committed");
    clients.forEach((c: any) => c.release());
    await pool.query({
      name: "post-by-id",
      text: "select title from posts where id=$1",
      values: [1],
    });
    log("Prepared statement executed");
    // LISTEN is connection-scoped, so reserve this client until the matching
    // notification arrives on its PostgreSQL session.
    const listener = await pool.connect();
    await listener.query("listen pgquic_demo");
    const notified = new Promise<void>((resolve) =>
      listener.once("notification", () => resolve()),
    );
    await pool.query("select pg_notify('pgquic_demo','hello from stream')");
    await notified;
    await listener.query("unlisten pgquic_demo");
    listener.release();
    log("LISTEN/NOTIFY crossed separate connections");
    const sleeper = await pool.connect();
    const query = sleeper.query(
      { text: "select pg_sleep(10)" },
      (error: Error) =>
        log(
          error
            ? "CancelRequest stopped pg_sleep"
            : "Sleep unexpectedly completed",
          Boolean(error),
        ),
    );
    await new Promise((r) => setTimeout(r, 500));
    // PostgreSQL cancellation is out-of-band: a temporary stream sends the
    // sleeping backend's process/secret pair.
    const canceller = new Client({
      transport,
      user: "browser_user",
      password: "development-only-password",
      database: "app",
      ssl: false,
      enableChannelBinding: false,
    } as any);
    canceller.cancel(sleeper, query);
    await new Promise((r) => setTimeout(r, 600));
    sleeper.release(true);
    log("Cancellation used a temporary WebTransport stream");
    const large = await pool.query(
      "select count(*) from generate_series(1,10000)",
    );
    log(
      `Large-result exercise returned ${large.rows[0].count} rows generated server-side`,
    );
  } catch (e) {
    actionableErrors(e).forEach((message) => log(message, false));
  } finally {
    ($("run") as HTMLButtonElement).disabled = false;
    render();
  }
}
$("run").addEventListener("click", () => void run());
$("recreate").addEventListener("click", async () => {
  await pool.end();
  await transport.close();
  try {
    create();
    log("Old session closed; next query will establish a new one");
  } catch (error) {
    actionableErrors(error).forEach((message) => log(message, false));
  }
});
if (!usableRuntime) ($("run") as HTMLButtonElement).disabled = true;
try {
  create();
} catch (error) {
  actionableErrors(error).forEach((message) => log(message, false));
}
